#!/usr/bin/env ruby

require 'lib/xml_format'
require 'lib/analysis'

#----------------------------------------------------------------

include XMLFormat

ARGV.each do |path|
  STDERR.puts "analysing #{path}"
  File.open(path, 'r') do |file|
    md = read_xml(file)
    analysis = MetadataAnalysis.new(md)
    analysis.fragmentations
  end
end

#----------------------------------------------------------------
