#!/usr/bin/env ruby

require 'lib/disk-units'
require 'lib/log'
require 'lib/tvm/tvm_api'
require 'lib/tvm/command_line'
require 'lib/tvm/dispatcher'

include DiskUnits
include Log
include TVM

#----------------------------------------------------------------

def top_level_handler(&block)
  begin
    block.call
  rescue => e
    STDERR.puts e.message
    exit 1
  end

  exit 0
end

#----------------------------------------------------------------

top_level_handler do
  open_log("./tvm.log")

  METADATA_FILE='./volumes.yaml'

  metadata = YAMLMetadata.new(METADATA_FILE)
  vm = VolumeManager.new(metadata)

  # We're always in an implicit transaction
  unless metadata.in_transaction?
    vm.begin
  end

  dispatcher = Dispatcher.new(vm)
  parse_command_line(dispatcher, *ARGV)

  metadata.persist
end

#----------------------------------------------------------------


